user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /dev/stderr;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;
    sendfile on;

    server {
        listen 8080;
        root /var/www/portfolio;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        location ~ /\. {
            deny all;
        }
    }
}
